### ISSUE TITLE
Should "Notify Compute Pressure Observers" take target types into consideration?

### ISSUE THREAD

**Issue by rakuco** [WICG/compute-pressure#66] opened 2022-02-25 12:37 UTC
https://wicg.github.io/compute-pressure/#notify-observers seems to notify all observers of all types when invoked, and it's not clear if that's desired. In other words, should an observer started via `observe('cpu')` also receive updates for GPUs?

**Comment by kenchris** [comment] 2022-02-25 12:56
In that case the RecordQueue should be empty - we probably instead need some text about when to add things to the RecordQueue depending on the observer type

> If records is not [empty](https://infra.spec.whatwg.org/#list-empty),

**Comment by kenchris** [comment] 2022-03-02 11:04
Reading through the latest spec, I believe this is fixed now. Can you check if you agree @rakuco ?

**Comment by rakuco** [comment] 2022-03-02 13:07
Let me see if I've understood it correctly when you have `observer1` observing CPU data and `observer2` observing GPU data. The CPU and GPU data might be collected from the platform and added to each observer's `[[QueuedRecords]]` at different rates. In this case, wouldn't it be possible that the queue for CPU data will be emptied when the implementation is reacting to a GPU update, since "notify compute pressure observers" will walk through all observers and queued records?

If I use the same observer to call `observe("cpu")` and `observe("gpu")`, it gets more confusing. The instance will have a single `[[QueuedRecords]]` for both target types and be in two different registered observer lists, one per target type.

AFAICS, this means that:
- GPU updates will be queued together with CPU updates, so even though https://wicg.github.io/compute-pressure/#notify-observers will empty `[[QueuedRecords]]` when processing the first observer list and the callback won't be called twice, the callback itself does not know if it's getting CPU or GPU records.
- Calling `takeRecords()` will retrieve GPU and CPU records all together.

Did I understand everything correctly? If so, is this all by design?

**Comment by kenchris** [comment] 2022-03-02 13:17
Yes this is by design (but see below), let me see if I understand what you are saying and whether we are agreeing :)

- the queued records are per observer, so updates will be queued for all observers observing data of that kind
- Updates are batched and callbacks invoked from the event loop task queue

But you got a point, I still have to add the type to the records, so that you can differentiate, just like PerformanceObserver does.

**Comment by kenchris** [comment] 2022-03-02 13:20
Filed https://github.com/WICG/compute-pressure/issues/70

**Comment by rakuco** [comment] 2022-03-02 13:28
> Yes this is by design (but see below), let me see if I understand what you are saying and whether we are agreeing :)
> 
> * the queued records are per observer, so updates will be queued for all observers observing data of that kind
> * Updates are batched and callbacks invoked from the event loop task queue

Yep. Additionally, an update to one observer of a given target will trigger updates to all other observers, including those of different types (if they have any queued data to send).

**Comment by kenchris** [comment] 2022-03-02 13:30
> Yep. Additionally, an update to one observer of a given target will trigger updates to all other observers, including those of different types (if they have any queued data to send).

If they have queued data, a task will already have been scheduled :-)

**Comment by rakuco** [comment] 2022-03-02 13:32
> > Yep. Additionally, an update to one observer of a given target will trigger updates to all other observers, including those of different types (if they have any queued data to send).
> 
> If they have queued data, a task will already have been scheduled :-)

Hmm, in this case under what circumstances will `[[QueuedRecords]]` have more than 1 entry?

**Comment by kenchris** [comment] 2022-03-02 13:36
>Hmm, in this case under what circumstances will [[QueuedRecords]] have more than 1 entry? 

Let me make a somewhat exaggerated example :-) I get a new pressure event every 1 second, but the JS that I am running takes 10 seconds to complete. So during those 10 seconds 10 data updates are scheduled and one task (as we check if one is already queued). When code completes, the event loop proceeds, now it might handle event handlers (can maybe also have 2 seconds and additional updates might be added), then it proceeds tasks queues and eventually gets to ours.

**Comment by rakuco** [comment] 2022-03-02 13:39
I guess this ticket can be closed while the rest of the work is tracked in #70, right?

**Comment by kenchris** [comment] 2022-03-02 13:39
Indeed, let me close it!

**Closed by kenchris** 2022-03-02 13:39 UTC
